 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
 package finalProject;

import java.io.Serializable;

import javafx.scene.layout.VBox;

public class SerializableVBox extends VBox implements Serializable {

        /** the version ID for serializing **/
	private static final long serialVersionUID = -8274170900300199913L; // v1 UID
   
   public static javafx.scene.layout.Priority getVgrow(javafx.scene.Node arg0) {
     return null;
   }
   
   public static void setMargin(javafx.scene.Node arg0, javafx.geometry.Insets arg1) {
   }
   
   public static javafx.geometry.Insets getMargin(javafx.scene.Node arg0) {
     return null;
   }
   
   public static void clearConstraints(javafx.scene.Node arg0) {
   }
   
   public SerializableVBox() {
   }
   
   public SerializableVBox(double arg0) {
   }
   
   public SerializableVBox(javafx.scene.Node... arg0) {
   }
   
   public SerializableVBox(double arg0, javafx.scene.Node... arg1) {
   }
   
   public javafx.geometry.Orientation getContentBias() {
     return null;
   }
   
   protected double computeMinWidth(double arg0) {
     return 0;
   }
   
   protected double computeMinHeight(double arg0) {
     return 0;
   }
   
   protected double computePrefWidth(double arg0) {
     return 0;
   }
   
   protected double computePrefHeight(double arg0) {
     return 0;
   }
   
   public void requestLayout() {
   }
   
   protected void layoutChildren() {
   }
   
   public static  java.util.List<javafx.css.CssMetaData<? extends javafx.css.Styleable,?>> getClassCssMetaData() {
     return null;
   }
   
   public  java.util.List<javafx.css.CssMetaData<? extends javafx.css.Styleable,?>> getCssMetaData() {
     return null;
   }

   static {} {
   }
 }